### PR TITLE
Add Glowstone support

### PR DESCRIPTION
**Pull request by aramperes**
This PR adds native support for the [Glowstone](https://github.com/GlowstoneMC/Glowstone) server software. It depends on the `2017.6.1` version we released at the end of June, and we continue to push updates at the end of every month.

Since Glowstone is a complete rewrite of the Vanilla software, it is not possible to use plugins which depend solely on NMS/OBC packages. So, I used reflection here to check if the current platform is a Glowstone server, as well as using native Glowstone methods to achieve the same functionality. I tested it personally and I did not see any difference.

If you'd like to chat more directly, feel free to contact us on [Discord](https://discord.gg/TFJqhsC)!

### CODE REVIEW

**Comment by aramperes** [comment]
@ConnorLinfoot are you planning to merge this?

**Comment by ConnorLinfoot** [comment]
I don't know how but I've only just seen this, I will try and test it and make sure nothing breaks on any Bukkit versions it works with. As long as everything is stable I'll merge 😄

**Comment by aramperes** [comment]
If you are still interested in merging this, I can update the changes to the latest version of Glowstone.

**Comment by arklanq** [comment]
I am also interested in using TitleAPI with Glowstone. Please merge this.

**Pull request closed without merging**
